#define uint16 unsigned short

extern "C" {
short __stdcall stGetBitmapResolution();
short __stdcall stSetBitmapResolution(short newValue);
LPCSTR __stdcall stGetDebugTraceFile();
LPCSTR __stdcall stSetDebugTraceFile(LPCSTR lpszNewValue);
LPCSTR __stdcall stGetLicenseKey();
LPCSTR __stdcall stSetLicenseKey(LPCSTR lpszNewValue);
long __stdcall stGetLineJump();
long __stdcall stSetLineJump(long nNewValue);
double __stdcall stGetLowerRatio();
double __stdcall stSetLowerRatio(double newValue);
short __stdcall stGetMinOccurrence();
short __stdcall stSetMinOccurrence(short nNewValue);
BOOL __stdcall stGetMultipleRead();
BOOL __stdcall stSetMultipleRead(BOOL bNewValue);
short __stdcall stGetNoiseReduction();
short __stdcall stSetNoiseReduction(short nNewValue);
short __stdcall stGetPageNo();
short __stdcall stSetPageNo(short nNewValue);
short __stdcall stGetPrefOccurrence();
short __stdcall stSetPrefOccurrence(short nNewValue);
short __stdcall stGetQuietZoneSize();
short __stdcall stSetQuietZoneSize(short nNewValue);
short __stdcall stGetRotation();
short __stdcall stSetRotation(short nNewValue);
double __stdcall stGetUpperRatio();
double __stdcall stSetUpperRatio(double newValue);
BOOL __stdcall stGetReadCode39();
BOOL __stdcall stSetReadCode39(BOOL bNewValue);
BOOL __stdcall stGetReadEAN13();
BOOL __stdcall stSetReadEAN13(BOOL bNewValue);
BOOL __stdcall stGetReadEAN8();
BOOL __stdcall stSetReadEAN8(BOOL bNewValue);
BOOL __stdcall stGetReadUPCA();
BOOL __stdcall stSetReadUPCA(BOOL bNewValue);
BOOL __stdcall stGetReadUPCE();
BOOL __stdcall stSetReadUPCE(BOOL bNewValue);
BOOL __stdcall stGetShowCheckDigit();
BOOL __stdcall stSetShowCheckDigit(BOOL bNewValue);
BOOL __stdcall stGetReadCode128();
BOOL __stdcall stGetReadShortCode128();
BOOL __stdcall stSetReadCode128(BOOL bNewValue);
BOOL __stdcall stSetReadShortCode128(BOOL bNewValue);
BOOL __stdcall stGetCode39NeedStartStop();
BOOL __stdcall stSetCode39NeedStartStop(BOOL bNewValue);
BOOL __stdcall stGetReadCode25();
BOOL __stdcall stSetReadCode25(BOOL bNewValue);
short __stdcall stGetColorThreshold();
short __stdcall stSetColorThreshold(short nNewValue);
LPCSTR __stdcall stGetBarString(short index);
short __stdcall stScanBarCode(LPCSTR file);
short __stdcall stScanBarCodeFromBitmap(long hBitmap);
LPCSTR __stdcall stGetBarStringType(short index);
short __stdcall stGetBarStringPos(short nBarCode, long FAR* pTopLeftX, long FAR* pTopLeftY, long FAR* pBotRightX, long FAR* pBotRightY);
BOOL __stdcall stSetScanRect(long TopLeftX, long TopLeftY, long BottomRightX, long BottomRightY, short MappingMode);
BOOL __stdcall stGetReadPatchCodes();
BOOL __stdcall stSetReadPatchCodes(BOOL bNewValue);
BOOL __stdcall stSaveBitmap(long hBitmap, LPCSTR strFilePath);
BOOL __stdcall stGetUseOverSampling();
BOOL __stdcall stSetUseOverSampling(BOOL bNewValue);
short __stdcall stGetScanDirection();
short __stdcall stSetScanDirection(short bNewValue);
long __stdcall stLoadTIFImage(char *file, uint16 nPage, uint16 *pbPhotoMetric) ;
long __stdcall stLibBarCodeFree(void *ptr) ;
short __stdcall stGetTIFPageCount(LPCSTR	file) ;
int __stdcall RegisterOCX(HWND hWnd, LPLONG lpIvalue, LPSTR lpszValue) ;
short __stdcall stGetMinLength() ;
short __stdcall stSetMinLength(short sNewValue) ;
short __stdcall stGetShortCode128MinLength() ;
short __stdcall stSetShortCode128MinLength(short sNewValue) ;
short __stdcall stGetMaxLength() ;
short __stdcall stSetMaxLength(short sNewValue) ;
LPCSTR __stdcall stSetTifSplitPath(LPCSTR szPath) ;
LPCSTR __stdcall stGetTifSplitPath() ;
short __stdcall stGetTifSplitMode() ;
short __stdcall stSetTifSplitMode(short sNewValue) ;
BOOL __stdcall stGetReadCodabar() ;
BOOL __stdcall stSetReadCodabar(BOOL bNewValue) ;
short __stdcall stGetBarStringDirection(short nBarCode) ;
BOOL __stdcall stGetConvertUPCEToEAN13() ;
BOOL __stdcall stSetConvertUPCEToEAN13(BOOL bNewValue) ;
short __stdcall stScanBarCodeFromBitmapDump(LPCSTR strFilePath) ;
int __stdcall stGetBarStringA (short index, LPSTR pBarCode, int length) ;
short __stdcall stGetSkewTolerance() ;
short __stdcall stSetSkewTolerance(short sNewValue) ;
short __stdcall stScanBarCodeFromDIB(long hDIB) ;
BOOL __stdcall stGetReadCode25ni() ;
BOOL __stdcall stSetReadCode25ni(BOOL bNewValue) ;
long __stdcall stLoadJPEGImage(char *file, uint16 *pbPhotoMetric) ;
long __stdcall stLoadPNGImage(char *file, uint16 *pbPhotoMetric) ;
long __stdcall stLoadGIFImage(char *file, uint16 *pbPhotoMetric) ;
LPCSTR __stdcall stGetPDFTool() ;
long __stdcall stLoadPDFImage(char *file, uint16 nPage, int *pPageCount, uint16 *pbPhotoMetric, int license) ;
HBITMAP __stdcall stLoadPDFImageH(char *file, uint16 nPage, int *pPageCount, uint16 *pbPhotoMetric, int license) ;
short __stdcall stSetPDFTool(LPCSTR pdfTool) ;
BOOL __stdcall stSaveDIBtoBMP(long hDIB, LPCSTR strFilePath) ;
BOOL __stdcall stSetPhotometric(BOOL bPhotometric) ;
BOOL __stdcall stSetAllowDuplicateValues(BOOL bNewValue) ;
BOOL __stdcall stGetAllowDuplicateValues() ;
BOOL __stdcall stSetDespeckle(BOOL bNewValue) ;
BOOL __stdcall stGetDespeckle() ;
BOOL __stdcall stGetReadPDF417();
BOOL __stdcall stSetReadPDF417(BOOL bNewValue);
BOOL __stdcall stGetReadMicroPDF417();
BOOL __stdcall stSetReadMicroPDF417(BOOL bNewValue);


HANDLE __stdcall mtCreateBarcodeInstance() ;
HANDLE __stdcall mtDestroyBarcodeInstance(HANDLE hBarcode) ;
short __stdcall mtGetBitmapResolution(HANDLE hBarcode);
short __stdcall mtSetBitmapResolution(HANDLE hBarcode, short newValue);
LPCSTR __stdcall mtGetDebugTraceFile(HANDLE hBarcode);
LPCSTR __stdcall mtSetDebugTraceFile(HANDLE hBarcode, LPCSTR lpszNewValue);
LPCSTR __stdcall mtGetLicenseKey(HANDLE hBarcode);
LPCSTR __stdcall mtSetLicenseKey(HANDLE hBarcode, LPCSTR lpszNewValue);
long __stdcall mtGetLineJump(HANDLE hBarcode);
long __stdcall mtSetLineJump(HANDLE hBarcode, long nNewValue);
double __stdcall mtGetLowerRatio(HANDLE hBarcode);
double __stdcall mtSetLowerRatio(HANDLE hBarcode, double newValue);
short __stdcall mtGetMinOccurrence(HANDLE hBarcode);
short __stdcall mtSetMinOccurrence(HANDLE hBarcode, short nNewValue);
BOOL __stdcall mtGetMultipleRead(HANDLE hBarcode);
BOOL __stdcall mtSetMultipleRead(HANDLE hBarcode, BOOL bNewValue);
short __stdcall mtGetNoiseReduction(HANDLE hBarcode);
short __stdcall mtSetNoiseReduction(HANDLE hBarcode, short nNewValue);
short __stdcall mtGetPageNo(HANDLE hBarcode);
short __stdcall mtSetPageNo(HANDLE hBarcode, short nNewValue);
short __stdcall mtGetPrefOccurrence(HANDLE hBarcode);
short __stdcall mtSetPrefOccurrence(HANDLE hBarcode, short nNewValue);
short __stdcall mtGetQuietZoneSize(HANDLE hBarcode);
short __stdcall mtSetQuietZoneSize(HANDLE hBarcode, short nNewValue);
short __stdcall mtGetRotation(HANDLE hBarcode);
short __stdcall mtSetRotation(HANDLE hBarcode, short nNewValue);
double __stdcall mtGetUpperRatio(HANDLE hBarcode);
double __stdcall mtSetUpperRatio(HANDLE hBarcode, double newValue);
BOOL __stdcall mtGetReadCode39(HANDLE hBarcode);
BOOL __stdcall mtSetReadCode39(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetReadEAN13(HANDLE hBarcode);
BOOL __stdcall mtSetReadEAN13(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetReadEAN8(HANDLE hBarcode);
BOOL __stdcall mtSetReadEAN8(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetReadUPCA(HANDLE hBarcode);
BOOL __stdcall mtSetReadUPCA(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetReadUPCE(HANDLE hBarcode);
BOOL __stdcall mtSetReadUPCE(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetShowCheckDigit(HANDLE hBarcode);
BOOL __stdcall mtSetShowCheckDigit(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetReadCode128(HANDLE hBarcode);
BOOL __stdcall mtSetReadCode128(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetReadShortCode128(HANDLE hBarcode);
BOOL __stdcall mtSetReadShortCode128(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetCode39NeedStartStop(HANDLE hBarcode);
BOOL __stdcall mtSetCode39NeedStartStop(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetReadCode25(HANDLE hBarcode);
BOOL __stdcall mtSetReadCode25(HANDLE hBarcode, BOOL bNewValue);
short __stdcall mtGetColorThreshold(HANDLE hBarcode);
short __stdcall mtSetColorThreshold(HANDLE hBarcode, short nNewValue);
LPCSTR __stdcall mtGetBarString(HANDLE hBarcode, short index);
short __stdcall mtScanBarCode(HANDLE hBarcode, LPCSTR file);
short __stdcall mtScanBarCodeFromBitmap(HANDLE hBarcode, long hBitmap);
LPCSTR __stdcall mtGetBarStringType(HANDLE hBarcode, short index);
short __stdcall mtGetBarStringPos(HANDLE hBarcode, short nBarCode, long FAR* pTopLeftX, long FAR* pTopLeftY, long FAR* pBotRightX, long FAR* pBotRightY);
BOOL __stdcall mtSetScanRect(HANDLE hBarcode, long TopLeftX, long TopLeftY, long BottomRightX, long BottomRightY, short MappingMode);
BOOL __stdcall mtGetReadPatchCodes(HANDLE hBarcode);
BOOL __stdcall mtSetReadPatchCodes(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetUseOverSampling(HANDLE hBarcode);
BOOL __stdcall mtSetUseOverSampling(HANDLE hBarcode, BOOL bNewValue);
short __stdcall mtGetScanDirection(HANDLE hBarcode);
short __stdcall mtSetScanDirection(HANDLE hBarcode, short bNewValue);
long __stdcall mtLoadTIFImage(HANDLE hBarcode, char *file, uint16 nPage, uint16 *pbPhotoMetric) ;
short __stdcall mtGetTIFPageCount(HANDLE hBarcode, char *file) ;
short __stdcall mtGetMinLength(HANDLE hBarcode) ;
short __stdcall mtSetMinLength(HANDLE hBarcode, short sNewValue) ;
short __stdcall mtGetShortCode128MinLength(HANDLE hBarcode) ;
short __stdcall mtSetShortCode128MinLength(HANDLE hBarcode, short sNewValue) ;
short __stdcall mtGetMaxLength(HANDLE hBarcode) ;
short __stdcall mtSetMaxLength(HANDLE hBarcode, short sNewValue) ;
LPCSTR __stdcall mtSetTifSplitPath(HANDLE hBarcode, LPCSTR szPath) ;
LPCSTR __stdcall mtGetTifSplitPath(HANDLE hBarcode) ;
short __stdcall mtGetTifSplitMode(HANDLE hBarcode) ;
short __stdcall mtSetTifSplitMode(HANDLE hBarcode, short sNewValue) ;
BOOL __stdcall mtGetReadCodabar(HANDLE hBarcode) ;
BOOL __stdcall mtSetReadCodabar(HANDLE hBarcode, BOOL bNewValue) ;
short __stdcall mtGetBarStringDirection(HANDLE hBarcode, short nBarCode) ;
BOOL __stdcall mtGetConvertUPCEToEAN13(HANDLE hBarcode) ;
BOOL __stdcall mtSetConvertUPCEToEAN13(HANDLE hBarcode, BOOL bNewValue) ;
short __stdcall mtScanBarCodeFromBitmapDump(HANDLE hBarcode, LPCSTR strFilePath) ;
int __stdcall mtGetBarStringA (HANDLE hBarcode, short index, LPSTR pBarCode, int length) ;
short __stdcall mtGetSkewTolerance(HANDLE hBarcode) ;
short __stdcall mtSetSkewTolerance(HANDLE hBarcode, short sNewValue) ;
short __stdcall mtScanBarCodeFromDIB(HANDLE hBarcode, long hDIB) ;
BOOL __stdcall mtGetReadCode25ni(HANDLE hBarcode) ;
BOOL __stdcall mtSetReadCode25ni(HANDLE hBarcode, BOOL bNewValue) ;
long __stdcall mtLoadJPEGImage(HANDLE hBarcode, char *file, uint16 *pbPhotoMetric) ;
long __stdcall mtLoadPNGImage(HANDLE hBarcode, char *file, uint16 *pbPhotoMetric) ;
long __stdcall mtLoadGIFImage(HANDLE hBarcode, char *file, uint16 *pbPhotoMetric) ;
BOOL __stdcall mtSetPhotometric(HANDLE hBarcode, BOOL bPhotometric) ;
BOOL __stdcall stGetPhotometric() ;
BOOL __stdcall mtGetPhotometric(HANDLE hBarcode) ;
long __stdcall mtLoadPDFImage(HANDLE hBarcode, char *file, uint16 nPage, int *pPageCount, uint16 *pbPhotoMetric, int license) ;
HBITMAP __stdcall mtLoadPDFImageH(HANDLE hBarcode, char *file, uint16 nPage, int *pPageCount, uint16 *pbPhotoMetric, int license) ;
short __stdcall mtSetPDFTool(HANDLE hBarcode, LPCSTR pdfTool) ;
LPCSTR __stdcall mtGetPDFTool(HANDLE hBarcode) ;
BOOL __stdcall mtSetAllowDuplicateValues(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall mtGetAllowDuplicateValues(HANDLE hBarcode) ;
BOOL __stdcall mtSetDespeckle(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall mtGetDespeckle(HANDLE hBarcode) ;
BOOL __stdcall stSetTempFolder(LPCSTR strTempFolder) ;
short __stdcall stGetMinSeparation() ;
short __stdcall stSetMinSeparation(short nNewValue) ;
short __stdcall mtGetMinSeparation(HANDLE hBarcode) ;
short __stdcall mtSetMinSeparation(HANDLE hBarcode, short nNewValue) ;
short __stdcall mtGetBarCodeConfidence(HANDLE hBarcode, short nBarcode) ;
short __stdcall stGetBarCodeConfidence(short nBarcode) ;
short __stdcall mtGetBarStringQualityScore(HANDLE hBarcode, short nBarcode) ;
short __stdcall stGetBarStringQualityScore(short nBarcode) ;
short __stdcall stConvertCode39Extended(LPSTR strBarcode) ;
BOOL __stdcall stSetExtendedCode39(BOOL bNewValue) ;
BOOL __stdcall mtSetExtendedCode39(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall stGetExtendedCode39() ;
BOOL __stdcall mtGetExtendedCode39(HANDLE hBarcode) ;
BOOL __stdcall stSetCode39Checksum(BOOL bNewValue) ;
BOOL __stdcall mtSetCode39Checksum(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall stGetCode39Checksum() ;
BOOL __stdcall mtGetCode39Checksum(HANDLE hBarcode) ;
BOOL __stdcall stSetErrorCorrection(BOOL bNewValue) ;
BOOL __stdcall mtSetErrorCorrection(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall stGetErrorCorrection() ;
BOOL __stdcall mtGetErrorCorrection(HANDLE hBarcode) ;
BOOL __stdcall stSetReadNumeric(BOOL bNewValue) ;
BOOL __stdcall mtSetReadNumeric(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall stGetReadNumeric() ;
BOOL __stdcall mtGetReadNumeric(HANDLE hBarcode) ;
LPCSTR __stdcall stSetPattern(LPCSTR lpszNewValue) ;
LPCSTR __stdcall mtSetPattern(HANDLE hBarcode, LPCSTR lpszNewValue) ;
LPCSTR __stdcall stGetPattern() ;
LPCSTR __stdcall mtGetPattern(HANDLE hBarcode) ;
short __stdcall stIsEval(int n) ;
short __stdcall stSetPdfBpp(short nNewValue) ;
short __stdcall mtSetPdfBpp(HANDLE hBarcode, short nNewValue) ;
short __stdcall stGetPdfBpp() ;
short __stdcall mtGetPdfBpp(HANDLE hBarcode) ;
short __stdcall stSetPdfDpi(short nNewValue) ;
short __stdcall mtSetPdfDpi(HANDLE hBarcode, short nNewValue) ;
short __stdcall stGetPdfDpi() ;
short __stdcall mtGetPdfDpi(HANDLE hBarcode) ;
short __stdcall stSetMinSpaceBarWidth(short nNewValue) ;
short __stdcall mtSetMinSpaceBarWidth(HANDLE hBarcode, short nNewValue) ;
short __stdcall stGetMinSpaceBarWidth() ;
short __stdcall mtGetMinSpaceBarWidth(HANDLE hBarcode) ;
BOOL __stdcall mtGetReadPDF417(HANDLE hBarcode);
BOOL __stdcall mtSetReadPDF417(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall mtGetReadMicroPDF417(HANDLE hBarcode);
BOOL __stdcall mtSetReadMicroPDF417(HANDLE hBarcode, BOOL bNewValue);
BOOL __stdcall stGetMedianFilter();
BOOL __stdcall stSetMedianFilter(BOOL bNewValue);
BOOL __stdcall mtGetMedianFilter(HANDLE hBarcode);
BOOL __stdcall mtSetMedianFilter(HANDLE hBarcode, BOOL bNewValue);
int __stdcall stSaveResults(LPCSTR filePath);
int __stdcall mtSaveResults(HANDLE hBarcode, LPCSTR filePath);
int __stdcall stLoadXMLSettings(LPCSTR filePath, unsigned char silent)  ;
int __stdcall mtLoadXMLSettings(HANDLE hBarcode, LPCSTR filePath, unsigned char silent) ;
int __stdcall stExportXMLSettings(LPCSTR filePath) ;
int __stdcall mtExportXMLSettings(HANDLE hBarcode, LPCSTR filePath) ;
int __stdcall stProcessXML(LPCSTR inputFilePath, LPCSTR outputFilePath, unsigned char silent) ;
int __stdcall mtProcessXML(HANDLE hBarcode, LPCSTR inputFilePath, LPCSTR outputFilePath, unsigned char silent) ;
void * __stdcall win32STCreateBarCodeSession() ;
void __stdcall win32STFreeBarCodeSession(void *hBarcode) ;
int __stdcall win32STReadBarCode(void *hBarcode, char *file, char *type, char ***bar_codes, char ***bar_codes_type) ;
void __stdcall	win32STSetParameter(void *hBarcode, uint16 param, void *value) ;
void __stdcall win32STGetParameter(void *hBarcode, uint16 param, void *value) ;
BOOL __stdcall stGetCode25Checksum() ;
BOOL __stdcall stSetCode25Checksum(BOOL bNewValue) ;
BOOL __stdcall mtGetCode25Checksum(HANDLE hBarcode) ;
BOOL __stdcall mtSetCode25Checksum(HANDLE hBarcode, BOOL bNewValue) ;
short __stdcall stSetEncoding(short nNewValue) ;
short __stdcall mtSetEncoding(HANDLE hBarcode, short nNewValue) ;
short __stdcall stGetEncoding() ;
short __stdcall mtGetEncoding(HANDLE hBarcode) ;
short __stdcall stSetGammaCorrection(short nNewValue) ;
short __stdcall mtSetGammaCorrection(HANDLE hBarcode, short nNewValue) ;
short __stdcall stGetGammaCorrection() ;
short __stdcall mtGetGammaCorrection(HANDLE hBarcode) ;
short __stdcall stSetSkewLineJump(short nNewValue) ;
short __stdcall mtSetSkewLineJump(HANDLE hBarcode, short nNewValue) ;
short __stdcall stGetSkewLineJump() ;
short __stdcall mtGetSkewLineJump(HANDLE hBarcode) ;
BOOL __stdcall stSetReadDataMatrix(BOOL bNewValue) ;
BOOL __stdcall mtSetReadDataMatrix(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall stGetReadDataMatrix() ;
BOOL __stdcall mtGetReadDataMatrix(HANDLE hBarcode) ;
BOOL __stdcall stSetReadQRCode(BOOL bNewValue) ;
BOOL __stdcall mtSetReadQRCode(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall stGetReadQRCode() ;
BOOL __stdcall mtGetReadQRCode(HANDLE hBarcode) ;
BOOL __stdcall stSetReadDatabar(BOOL bNewValue) ;
BOOL __stdcall mtSetReadDatabar(HANDLE hBarcode, BOOL bNewValue) ;
BOOL __stdcall stGetReadDatabar() ;
BOOL __stdcall mtGetReadDatabar(HANDLE hBarcode) ;
short __stdcall stSetColorProcessingLevel(short value) ;
short __stdcall mtSetColorProcessingLevel(HANDLE hBarcode, short value) ;
short __stdcall stGetColorProcessingLevel() ;
short __stdcall mtGetColorProcessingLevel(HANDLE hBarcode) ;
short __stdcall stSetDatabarOptions(short value) ;
short __stdcall mtSetDatabarOptions(HANDLE hBarcode, short value) ;
short __stdcall stGetDatabarOptions() ;
short __stdcall mtGetDatabarOptions(HANDLE hBarcode) ;
short __stdcall stSetPdfImageOnly(short value) ;
short __stdcall mtSetPdfImageOnly(HANDLE hBarcode, short value) ;
short __stdcall stGetPdfImageOnly() ;
short __stdcall mtGetPdfImageOnly(HANDLE hBarcode) ;
short __stdcall stSetReadCode93(short value) ;
short __stdcall mtSetReadCode93(HANDLE hBarcode, short value) ;
short __stdcall stGetReadCode93() ;
short __stdcall mtGetReadCode93(HANDLE hBarcode) ;
short __stdcall stSetPdfImageExtractOptions(short value) ;
short __stdcall mtSetPdfImageExtractOptions(HANDLE hBarcode, short value) ;
short __stdcall stGetPdfImageExtractOptions() ;
short __stdcall mtGetPdfImageExtractOptions(HANDLE hBarcode) ;
short __stdcall stSetPdfImageRasterOptions(short value) ;
short __stdcall mtSetPdfImageRasterOptions(HANDLE hBarcode, short value) ;
short __stdcall stGetPdfImageRasterOptions() ;
short __stdcall mtGetPdfImageRasterOptions(HANDLE hBarcode) ;



BOOL __stdcall stGetUseFastScan();
BOOL __stdcall stSetUseFastScan(BOOL value);
BOOL __stdcall mtGetUseFastScan(HANDLE hBarcode);
BOOL __stdcall mtSetUseFastScan(HANDLE hBarcode, BOOL value);
BOOL __stdcall stGetBarcodesAtTopOfPage();
BOOL __stdcall stSetBarcodesAtTopOfPage(BOOL value);
BOOL __stdcall mtGetBarcodesAtTopOfPage(HANDLE hBarcode);
BOOL __stdcall mtSetBarcodesAtTopOfPage(HANDLE hBarcode, BOOL value);
short __stdcall stGetFastScanLineJump();
short __stdcall stSetFastScanLineJump(short value);
short __stdcall mtGetFastScanLineJump(HANDLE hBarcode);
short __stdcall mtSetFastScanLineJump(HANDLE hBarcode, short value);
short __stdcall stGetMaxBarcodesPerPage();
short __stdcall stSetMaxBarcodesPerPage(short value);
short __stdcall mtGetMaxBarcodesPerPage(HANDLE hBarcode);
short __stdcall mtSetMaxBarcodesPerPage(HANDLE hBarcode, short value);
BOOL __stdcall stGetSkewedDatamatrix();
BOOL __stdcall stSetSkewedDatamatrix(BOOL value);
BOOL __stdcall mtGetSkewedDatamatrix(HANDLE hBarcode);
BOOL __stdcall mtSetSkewedDatamatrix(HANDLE hBarcode, BOOL value);
int __stdcall stGetTimeOut();
int __stdcall stSetTimeOut(int value);
int __stdcall mtGetTimeOut(HANDLE hBarcode);
int __stdcall mtSetTimeOut(HANDLE hBarcode, int value);
BOOL __stdcall stGetSkewedLinear();
BOOL __stdcall stSetSkewedLinear(BOOL value);
BOOL __stdcall mtGetSkewedLinear(HANDLE hBarcode);
BOOL __stdcall mtSetSkewedLinear(HANDLE hBarcode, BOOL value);
short __stdcall stGetReportUnreadBarcodes();
short __stdcall stSetReportUnreadBarcodes(short value);
short __stdcall mtGetReportUnreadBarcodes(HANDLE hBarcode);
short __stdcall mtSetReportUnreadBarcodes(HANDLE hBarcode, short value);
short __stdcall stGetShowCodabarStartStop();
short __stdcall stSetShowCodabarStartStop(short value);
short __stdcall mtGetShowCodabarStartStop(HANDLE hBarcode);
short __stdcall mtSetShowCodabarStartStop(HANDLE hBarcode, short value);

int __stdcall mtGetLastError(HANDLE hBarcode) ;
int __stdcall mtGetLastWinError(HANDLE hBarcode) ;


short __stdcall stScanBarCodeInBackground(LPCSTR file);
short __stdcall mtScanBarCodeInBackground(HANDLE hBarcode, LPCSTR file);
short __stdcall stScanBarCodeWait(int milliSeconds);
short __stdcall mtScanBarCodeWait(HANDLE hBarcode, int milliSeconds);
short __stdcall stGetBarCodeCount();
short __stdcall mtGetBarCodeCount(HANDLE hBarcode);
short __stdcall stScanBarCodeAbort();
short __stdcall mtScanBarCodeAbort(HANDLE hBarcode);
int __stdcall stGetProgress();
int __stdcall mtGetProgress(HANDLE hBarcode);
short __stdcall mtGetScanExitCode(HANDLE hBarcode);

short __stdcall stGetMaxThreads();
short __stdcall stSetMaxThreads(short value);
short __stdcall mtGetMaxThreads(HANDLE hBarcode);
short __stdcall mtSetMaxThreads(HANDLE hBarcode, short val);

BOOL __stdcall stGetRotateBy45IfNoBarcode();
BOOL __stdcall stSetRotateBy45IfNoBarcode(BOOL value);
BOOL __stdcall mtGetRotateBy45IfNoBarcode(HANDLE hBarcode);
BOOL __stdcall mtSetRotateBy45IfNoBarcode(HANDLE hBarcode, BOOL val);
short __stdcall stGetCode128DebugMode();
short __stdcall stSetCode128DebugMode(short value);
short __stdcall mtGetCode128DebugMode(HANDLE hBarcode);
short __stdcall mtSetCode128DebugMode(HANDLE hBarcode, short val);
BOOL __stdcall stGetCode128Lenient();
BOOL __stdcall stSetCode128Lenient(BOOL value);
BOOL __stdcall mtGetCode128Lenient(HANDLE hBarcode);
BOOL __stdcall mtSetCode128Lenient(HANDLE hBarcode, BOOL val);
short __stdcall stGetCode128SearchLevel();
short __stdcall stSetCode128SearchLevel(short value);
short __stdcall mtGetCode128SearchLevel(HANDLE hBarcode);
short __stdcall mtSetCode128SearchLevel(HANDLE hBarcode, short val);
short __stdcall stGetMedianFilterBias();
short __stdcall stSetMedianFilterBias(short value);
short __stdcall mtGetMedianFilterBias(HANDLE hBarcode);
short __stdcall mtSetMedianFilterBias(HANDLE hBarcode, short val);
BOOL __stdcall stGetPdf417Debug();
BOOL __stdcall stSetPdf417Debug(BOOL value);
BOOL __stdcall mtGetPdf417Debug(HANDLE hBarcode);
BOOL __stdcall mtSetPdf417Debug(HANDLE hBarcode, BOOL val);
short __stdcall stGetPdf417ChannelMode();
short __stdcall stSetPdf417ChannelMode(short value);
short __stdcall mtGetPdf417ChannelMode(HANDLE hBarcode);
short __stdcall mtSetPdf417ChannelMode(HANDLE hBarcode, short val);
short __stdcall stGetPdfLocking();
short __stdcall stSetPdfLocking(short value);
short __stdcall mtGetPdfLocking(HANDLE hBarcode);
short __stdcall mtSetPdfLocking(HANDLE hBarcode, short val);
BOOL __stdcall stGetQrCodeReadInverted();
BOOL __stdcall stSetQrCodeReadInverted(BOOL value);
BOOL __stdcall mtGetQrCodeReadInverted(HANDLE hBarcode);
BOOL __stdcall mtSetQrCodeReadInverted(HANDLE hBarcode, BOOL val);
short __stdcall stGetQuotedPrintableCharSet();
short __stdcall stSetQuotedPrintableCharSet(short value);
short __stdcall mtGetQuotedPrintableCharSet(HANDLE hBarcode);
short __stdcall mtSetQuotedPrintableCharSet(HANDLE hBarcode, short val);
BOOL __stdcall stGetWeightLongerBarcodes();
BOOL __stdcall stSetWeightLongerBarcodes(BOOL value);
BOOL __stdcall mtGetWeightLongerBarcodes(HANDLE hBarcode);
BOOL __stdcall mtSetWeightLongerBarcodes(HANDLE hBarcode, BOOL val);
short __stdcall stGetCode39MaxRatioPcnt();
short __stdcall stSetCode39MaxRatioPcnt(short value);
short __stdcall mtGetCode39MaxRatioPcnt(HANDLE hBarcode);
short __stdcall mtSetCode39MaxRatioPcnt(HANDLE hBarcode, short val);
short __stdcall stGetDataMatrixFinderGapTolerance();
short __stdcall stSetDataMatrixFinderGapTolerance(short value);
short __stdcall mtGetDataMatrixFinderGapTolerance(HANDLE hBarcode);
short __stdcall mtSetDataMatrixFinderGapTolerance(HANDLE hBarcode, short val);
BOOL __stdcall stGetDataMatrixAutoUTF8();
BOOL __stdcall stSetDataMatrixAutoUTF8(BOOL value);
BOOL __stdcall mtGetDataMatrixAutoUTF8(HANDLE hBarcode);
BOOL __stdcall mtSetDataMatrixAutoUTF8(HANDLE hBarcode, BOOL val);
short __stdcall stGetPatchCodeMinOccurrence();
short __stdcall stSetPatchCodeMinOccurrence(short value);
short __stdcall mtGetPatchCodeMinOccurrence(HANDLE hBarcode);
short __stdcall mtSetPatchCodeMinOccurrence(HANDLE hBarcode, short val);
BOOL __stdcall stGetPdf417AutoUTF8();
BOOL __stdcall stSetPdf417AutoUTF8(BOOL value);
BOOL __stdcall mtGetPdf417AutoUTF8(HANDLE hBarcode);
BOOL __stdcall mtSetPdf417AutoUTF8(HANDLE hBarcode, BOOL val);
BOOL __stdcall stGetPdf417MacroEscapeBackslash();
BOOL __stdcall stSetPdf417MacroEscapeBackslash(BOOL value);
BOOL __stdcall mtGetPdf417MacroEscapeBackslash(HANDLE hBarcode);
BOOL __stdcall mtSetPdf417MacroEscapeBackslash(HANDLE hBarcode, BOOL val);
BOOL __stdcall stGetQRCodeAutoUTF8();
BOOL __stdcall stSetQRCodeAutoUTF8(BOOL value);
BOOL __stdcall mtGetQRCodeAutoUTF8(HANDLE hBarcode);
BOOL __stdcall mtSetQRCodeAutoUTF8(HANDLE hBarcode, BOOL val);
BOOL __stdcall stGetQRCodeAutoMedianFilter();
BOOL __stdcall stSetQRCodeAutoMedianFilter(BOOL value);
BOOL __stdcall mtGetQRCodeAutoMedianFilter(HANDLE hBarcode);
BOOL __stdcall mtSetQRCodeAutoMedianFilter(HANDLE hBarcode, BOOL val);
BOOL __stdcall stGetUseOldCode128Algorithm();
BOOL __stdcall stSetUseOldCode128Algorithm(BOOL value);
BOOL __stdcall mtGetUseOldCode128Algorithm(HANDLE hBarcode);
BOOL __stdcall mtSetUseOldCode128Algorithm(HANDLE hBarcode, BOOL val);
BOOL __stdcall stGetUseRunCache();
BOOL __stdcall stSetUseRunCache(BOOL value);
BOOL __stdcall mtGetUseRunCache(HANDLE hBarcode);
BOOL __stdcall mtSetUseRunCache(HANDLE hBarcode, BOOL val);

}
